Ajuste controles storybook
David22zambrano/Storybook pull request #1
Opened 2024-09-10 21:35 UTC by danna222222

2024-09-11 20:29 UTC, David22zambrano requested changes

2024-09-11 20:29 UTC, David22zambrano commented on storybook/src/Theme/components.ts
> +// import { transform } from "typescript";
Lineas de codigo comentadas

2024-09-11 20:29 UTC, David22zambrano commented on storybook/src/Theme/components.ts
> +          color: "#fff",
Color quemado no, hay un color asi en las paletas

2024-09-11 20:29 UTC, David22zambrano commented on storybook/src/stories/Alert.stories.tsx
> +import "./Generales/tipografia.ts";
solo se importa generales, ya que  en "generales" se esta exportando todo lo que este dentro del esa carpeta. por eso generales tiene un index.ts exportando todo, para solo tener que importar Generales y ya

2024-09-11 20:29 UTC, David22zambrano commented on storybook/src/stories/DataGrid.stories.tsx
> +import "../Generales/tipografia.ts"
Solo se importa generales

2024-09-11 20:29 UTC, David22zambrano commented on storybook/src/stories/checkbox.stories.tsx
> +import "./Generales/tipografia.ts";
solo se importa generales ya que el mismo exporta todo

2024-09-11 20:29 UTC, David22zambrano commented on storybook/src/stories/drawer.stories.tsx
> +import "../Generales/tipografia.ts"
Solo se importa generales ya que el mismo exporta todo lo que contiene

2024-09-11 20:29 UTC, David22zambrano commented on storybook/src/stories/footerAction.stories.tsx
> +import "../Generales/tipografia.ts"
Solo se importa generales ya que el mismo exporta todo lo que contiene

2024-09-11 20:31 UTC, closed without merging

2024-09-12 20:06 UTC, danna222222 commented on storybook/src/Theme/components.ts
> +// import { transform } from "typescript";
Cambio realizado

2024-09-12 20:07 UTC, danna222222 commented on storybook/src/stories/Alert.stories.tsx
> +import "./Generales/tipografia.ts";
Cambio realizado

2024-09-12 20:07 UTC, danna222222 commented on storybook/src/stories/DataGrid.stories.tsx
> +import "../Generales/tipografia.ts"
Cambio realizado